export enum EquipmentTypeEnum {
    ANY = 'any',
    NONE = 'none',
    BARBELL = 'barbell',
    DUMBBELL = 'dumbbell',
    OTHER = 'other',
    BODY_ONLY = 'body only',
    CABLE = 'cable',
    MACHINE = 'machine',
    KETTLEBELLS = 'kettlebells',
    BANDS = 'bands',
    MEDICINE_BALL = 'medicine ball',
    EXERCISE_BALL = 'exercise ball',
    FOAM_ROLL = 'foam roll',
    E_Z_CURL_BAR = 'e-z curl bar',
}
