export enum MuscleGroupTypeEnum {
    ANY = 'any',
    QUADRICEPS = 'quadriceps',
    SHOULDERS = 'shoulders',
    ABDOMINALS = 'abdominals',
    CHEST = 'chest',
    HAMSTRINGS = 'hamstrings',
    TRICEPS = 'triceps',
    BICEPS = 'biceps',
    LATS = 'lats',
    MIDDLE_BACK = 'middle back',
    CALVES = 'calves',
    LOWER_BACK = 'lower back',
    FOREARMS = 'forearms',
    GLUTES = 'glutes',
    TRAPS = 'traps',
    ADDUCTORS = 'adductors',
    ABDUCTORS = 'abductors',
    NECK = 'neck',
}
